#!/usr/bin/env bash

# Check that dependencies are available
st37-dep "pv"


create_manifest() {
    
}

create_archive() {
    tar cf - "$1" -P | pv -s $(du -sb "$1" | awk '{print $1}') | gzip > "$2"
}

